#!/usr/bin/env zsh

local Command="$1"

shift

printf $_zpm_parallel_format "$@" | \
  ZPM_TMP_DIR="$ZPM_TMP_DIR" \
  _ZPM_PLUGINS_DIR="$_ZPM_PLUGINS_DIR" \
  _ZPM_autoload="$_ZPM_autoload" \
  ${(z)_zpm_parallel_launcher} "${_ZPM_DIR}/bin/@zpm-plugin-helper" $Command $_zpm_parallel_item
